name: Deploy API to Server

on:
  push:
    branches:
      - main  # تأكد أن اسم الفرع عندك main (لو master غيره هنا)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Files via SSH Key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # استخدام المفتاح الذي أضفته في Secrets
          port: 21098 # هذا البورت الشائع في ليبيا سبايدر (لو فشل غيره لـ 22)
          source: "."   
          target: "/home/alideboc/api.alidebo.com"
          rm: false     # لعدم مسح الملفات الموجودة مسبقاً مثل .env
          strip_components: 0